### ISSUE TITLE
The GC instructions are out of date, as are the images

### ISSUE THREAD

**Issue by Dannnno** [workshopper/scope-chains-closures#10]
The DevTools > Timeline tab in Chrome looks different now

![options](https://cloud.githubusercontent.com/assets/6121935/8944515/c9d9f09a-3546-11e5-84a1-cbc451b3c757.PNG)
![tools](https://cloud.githubusercontent.com/assets/6121935/8944535/e9348112-3546-11e5-8f17-a7c165f65947.PNG)

and I'm not sure which section to highlight for the memory dropping.

**Comment by jesstelford** [comment]
I just checked in Chrome Canary (v46), and everything is still the same.

It looks like you've incorrectly selected the "Frames View" button (the blue vertical lines). It should be unselected: 
![screen shot 2015-07-29 at 9 29 11 am](https://cloud.githubusercontent.com/assets/612020/8946519/629199a4-35d4-11e5-8f98-a4a3826cf9a2.png)

**Comment by Dannnno** [comment]
Equally as embarassing. Thank you!

**Comment by jesstelford** [comment]
I blame the silly little icon in DevTools - it's not clear what it actually is, and even I still have to look up their meanings occasionally.

**Comment by denizdogan** [comment]
I think this part of the tutorial could do with some improving, because it's not clear at all to me what e.g. "Click this drop in memory to select it" means. There's a lot of information in different places in the DevTools area and the tiny screenshot displaying what to click didn't help. I couldn't figure out where to click and what I was expected to see.
